// Copilot CLI harness setup
// Generates a user-level Copilot extension at ~/.copilot/extensions/meshwire.mjs
// using the proven joinSession() pattern from @github/copilot-sdk/extension.
//
// The extension reads credentials from ~/.meshwire/credentials.json and the
// per-workspace mesh from .mesh.json in the current directory.

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import chalk from 'chalk';
import { writeMeshJson, readMeshJson } from '../mesh-schema.js';
import { readCredentials } from '../auth.js';
import { MeshWireClient } from '../api.js';

const EXTENSION_DIR = join(homedir(), '.copilot', 'extensions');
const EXTENSION_FILE = join(EXTENSION_DIR, 'meshwire.mjs');

// ---------------------------------------------------------------------------
// Generated extension template
// ---------------------------------------------------------------------------
// IMPORTANT: This template intentionally mirrors the pattern of the canonical
// cloud-mesh extension Hector runs locally (~/.copilot/extensions/cloud-mesh):
//   - imports `joinSession` from @github/copilot-sdk/extension
//   - registers tools + hooks via a single joinSession({ ... }) call
//   - uses ASCII-only console output so Windows terminals never show mojibake
//   - includes a heartbeat + long-poll loop so messages route automatically
// Do NOT replace this with `export const tools` / `export const hooks` --
// Copilot CLI does not load that shape and the extension would silently no-op.

function buildExtensionSource({ meshwireUrl, meshId }) {
  return `// MeshWire -- Copilot CLI Extension
// Auto-generated by: meshwire init --harness copilot
// Reads credentials from ~/.meshwire/credentials.json
// Reads workspace mesh from .mesh.json in the current directory
//
// This file uses the joinSession() extension API from @github/copilot-sdk.

import { joinSession } from "@github/copilot-sdk/extension";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir } from "node:os";

// --- Configuration ---------------------------------------------------------
const BASE_URL = ${JSON.stringify(meshwireUrl)};
const DEFAULT_MESH_ID = ${JSON.stringify(meshId || '')};
const HEARTBEAT_INTERVAL_MS = 60_000;  // 1 minute
const POLL_INTERVAL_MS = 15_000;       // 15 seconds
const MAX_MESSAGE_SIZE = 10240;        // 10KB

// --- Credentials & workspace -----------------------------------------------
const CREDS_FILE = join(homedir(), ".meshwire", "credentials.json");

function loadCreds() {
  if (!existsSync(CREDS_FILE)) return null;
  try { return JSON.parse(readFileSync(CREDS_FILE, "utf8")); } catch { return null; }
}

function loadMeshJson() {
  const file = join(process.cwd(), ".mesh.json");
  if (!existsSync(file)) return null;
  try { return JSON.parse(readFileSync(file, "utf8")); } catch { return null; }
}

function activeMeshId() {
  return loadMeshJson()?.mesh_id || DEFAULT_MESH_ID || "";
}

// --- Offset persistence (per-mesh) -----------------------------------------
function offsetFile(meshId) {
  return join(homedir(), ".copilot", "extensions", "meshwire", \`offset-\${meshId}\`);
}

function loadOffset(meshId) {
  if (!meshId) return 0;
  try {
    const f = offsetFile(meshId);
    if (existsSync(f)) {
      const v = parseInt(readFileSync(f, "utf8").trim(), 10);
      return Number.isFinite(v) ? v : 0;
    }
  } catch { /* fresh start */ }
  return 0;
}

function saveOffset(meshId, offset) {
  if (!meshId) return;
  try {
    const f = offsetFile(meshId);
    const dir = dirname(f);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(f, String(offset), "utf8");
  } catch { /* best-effort */ }
}

// --- HTTP helper -----------------------------------------------------------
async function api(path, { method = "GET", body = null } = {}) {
  const creds = loadCreds();
  if (!creds?.token) throw new Error("Not authenticated. Run: meshwire login");
  const meshId = activeMeshId();
  const url = BASE_URL + path.replace("{meshId}", meshId);
  const opts = {
    method,
    headers: {
      "Authorization": "Bearer " + creds.token,
      "Content-Type": "application/json",
    },
  };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(url, opts);
  if (!res.ok) {
    const txt = await res.text().catch(() => "");
    let msg;
    try { msg = JSON.parse(txt).error; } catch { msg = txt || res.statusText; }
    throw new Error("MeshWire " + res.status + ": " + msg);
  }
  return res.json();
}

// --- State -----------------------------------------------------------------
let agentId = null;
let agentName = null;
let lastOffset = 0;
let heartbeatTimer = null;
let pollTimer = null;

// --- Registration ----------------------------------------------------------
async function registerAgent() {
  const meshJson = loadMeshJson();
  const meshId = meshJson?.mesh_id || DEFAULT_MESH_ID;
  if (!meshId) return null;

  agentName =
    meshJson?.agent_name ||
    (process.cwd().split(/[\\\\/]/).pop() || "copilot-cli");

  try {
    const result = await api("/mesh/{meshId}/agents", {
      method: "POST",
      body: {
        name: agentName,
        description: "GitHub Copilot CLI agent",
        workspace: meshJson?.workspace_name || agentName,
        metadata: {
          platform: "copilot-cli",
          harness: "meshwire",
          machine: process.env.COMPUTERNAME || process.env.HOSTNAME || "unknown",
          pid: process.pid,
        },
      },
    });
    agentId = result.agent_id;
    lastOffset = loadOffset(meshId);
    return result;
  } catch (err) {
    console.error("[meshwire] registration failed: " + err.message);
    return null;
  }
}

// --- Heartbeat -------------------------------------------------------------
function startHeartbeat() {
  if (heartbeatTimer) return;
  heartbeatTimer = setInterval(async () => {
    if (!agentId) return;
    try {
      await api("/mesh/{meshId}/agents/" + agentId + "/heartbeat", { method: "POST" });
    } catch { /* best-effort */ }
  }, HEARTBEAT_INTERVAL_MS);
}

function stopHeartbeat() {
  if (heartbeatTimer) { clearInterval(heartbeatTimer); heartbeatTimer = null; }
}

// --- Polling ---------------------------------------------------------------
function routeIncoming(msg) {
  const meshId = activeMeshId();
  const prompt =
    "[MeshWire -- Incoming Message]\\n" +
    "From: " + msg.sender_id + " (mesh: " + meshId + ")\\n" +
    "Priority: " + msg.priority + "\\n" +
    "Message ID: " + msg.message_id + "\\n" +
    "Sent: " + msg.created_at + "\\n\\n" +
    "Message:\\n" + msg.content + "\\n\\n" +
    "---\\n" +
    "To reply, call mesh_reply_to_message(message_id=" + msg.message_id + ", content=\\"...\\").";

  session.send({ prompt, mode: "immediate" }).catch((err) => {
    console.error("[meshwire] failed to route message " + msg.message_id + ": " + err.message);
  });
}

function startPolling() {
  if (pollTimer) return;
  pollTimer = setInterval(async () => {
    if (!agentId) return;
    const meshId = activeMeshId();
    if (!meshId) return;
    try {
      const params = new URLSearchParams({
        recipient: agentId,
        offset: String(lastOffset),
        timeout: "1",
        limit: "10",
      });
      const result = await api("/mesh/{meshId}/messages?" + params.toString());
      const messages = result.messages || [];
      if (messages.length === 0) return;
      const initial = lastOffset;
      for (const m of messages) {
        if (m.message_id > initial) {
          routeIncoming(m);
          if (m.message_id > lastOffset) lastOffset = m.message_id;
        }
      }
      if (lastOffset > initial) saveOffset(meshId, lastOffset);
    } catch { /* best-effort */ }
  }, POLL_INTERVAL_MS);
}

function stopPolling() {
  if (pollTimer) { clearInterval(pollTimer); pollTimer = null; }
}

// --- Join session ----------------------------------------------------------
const session = await joinSession({
  onPermissionRequest: "approveAll",

  hooks: {
    onSessionStart: async () => {
      const meshId = activeMeshId();
      let peerLine = "";
      if (agentId && meshId) {
        try {
          const peers = await api("/mesh/{meshId}/agents");
          const list = (peers.agents || [])
            .filter((a) => a.agent_id !== agentId)
            .map((a) => "  - " + a.name + " (" + (a.workspace || "unknown") + ")")
            .join("\\n");
          peerLine = list ? "\\nMesh peers:\\n" + list : "\\nNo other agents in this mesh yet.";
        } catch { /* best-effort */ }
      }
      return {
        additionalContext:
          "Connected to MeshWire mesh \\"" + (meshId || "(none)") + "\\" as \\"" +
          (agentName || "unregistered") + "\\" (agent_id: " + (agentId || "unregistered") + ")." +
          peerLine + "\\n" +
          "MeshWire base: " + BASE_URL + "\\n" +
          "Tools: mesh_send_message, mesh_reply_to_message, mesh_get_messages, mesh_list_agents, mesh_status",
      };
    },

    onSessionEnd: async () => {
      stopHeartbeat();
      stopPolling();
      return { cleanupActions: ["Stopped MeshWire heartbeat and polling"] };
    },
  },

  tools: [
    {
      name: "mesh_send_message",
      description:
        "Send a message to agents in the MeshWire mesh. Use recipient_id from mesh_list_agents, or '*' to broadcast.",
      parameters: {
        type: "object",
        properties: {
          recipient_id: { type: "string", description: "Target agent ID, or '*' for broadcast." },
          content: { type: "string", description: "Message content (max 10KB)." },
          priority: { type: "string", enum: ["urgent", "high", "normal", "low"], description: "Message priority (default: normal)." },
        },
        required: ["content"],
      },
      handler: async (args) => {
        if (!agentId) {
          return { textResultForLlm: "[X] Not registered with MeshWire mesh.", resultType: "failure" };
        }
        if ((args.content || "").length > MAX_MESSAGE_SIZE) {
          return { textResultForLlm: "[X] Message too large (" + args.content.length + " chars). Max " + MAX_MESSAGE_SIZE + ".", resultType: "failure" };
        }
        try {
          const result = await api("/mesh/{meshId}/messages", {
            method: "POST",
            body: {
              sender_id: agentId,
              recipient_id: args.recipient_id || "*",
              content: args.content,
              priority: args.priority || "normal",
            },
          });
          return {
            textResultForLlm:
              "[OK] Sent (id=" + result.message_id + ") to " + (args.recipient_id || "* (broadcast)") + ".",
            resultType: "success",
          };
        } catch (err) {
          return { textResultForLlm: "[X] Failed to send: " + err.message, resultType: "failure" };
        }
      },
    },

    {
      name: "mesh_reply_to_message",
      description: "Reply to a specific MeshWire message. Creates a threaded response.",
      parameters: {
        type: "object",
        properties: {
          message_id: { type: "integer", description: "The message_id to reply to." },
          content: { type: "string", description: "Reply content (max 10KB)." },
        },
        required: ["message_id", "content"],
      },
      handler: async (args) => {
        if (!agentId) {
          return { textResultForLlm: "[X] Not registered with MeshWire mesh.", resultType: "failure" };
        }
        if ((args.content || "").length > MAX_MESSAGE_SIZE) {
          return { textResultForLlm: "[X] Reply too large.", resultType: "failure" };
        }
        try {
          const result = await api("/mesh/{meshId}/messages/" + args.message_id + "/reply", {
            method: "POST",
            body: { sender_id: agentId, content: args.content },
          });
          return {
            textResultForLlm: "[OK] Reply sent (id=" + result.message_id + ") to message " + args.message_id + ".",
            resultType: "success",
          };
        } catch (err) {
          return { textResultForLlm: "[X] Failed to reply: " + err.message, resultType: "failure" };
        }
      },
    },

    {
      name: "mesh_get_messages",
      description: "Fetch recent MeshWire messages addressed to this agent.",
      parameters: {
        type: "object",
        properties: {
          limit: { type: "integer", description: "Max messages (default 20)." },
        },
      },
      handler: async (args) => {
        if (!agentId) {
          return { textResultForLlm: "[X] Not registered with MeshWire mesh.", resultType: "failure" };
        }
        try {
          const params = new URLSearchParams({
            recipient: agentId,
            offset: "0",
            timeout: "1",
            limit: String(args?.limit || 20),
          });
          const result = await api("/mesh/{meshId}/messages?" + params.toString());
          const messages = result.messages || [];
          if (messages.length === 0) {
            return { textResultForLlm: "No messages for this agent.", resultType: "success" };
          }
          const lines = ["MeshWire messages (" + messages.length + "):"];
          for (const m of messages) {
            const head = "  [" + m.message_id + "] from " + m.sender_id + " (" + m.priority + ", " + m.created_at + ")";
            const body = "    " + (m.content || "").slice(0, 200) + ((m.content || "").length > 200 ? "..." : "");
            lines.push(head, body);
          }
          return { textResultForLlm: lines.join("\\n"), resultType: "success" };
        } catch (err) {
          return { textResultForLlm: "[X] Failed to get messages: " + err.message, resultType: "failure" };
        }
      },
    },

    {
      name: "mesh_list_agents",
      description: "List all agents currently registered in the active MeshWire mesh.",
      parameters: { type: "object", properties: {} },
      handler: async () => {
        try {
          const result = await api("/mesh/{meshId}/agents");
          const agents = result.agents || [];
          if (agents.length === 0) {
            return { textResultForLlm: "No agents registered in this mesh.", resultType: "success" };
          }
          const lines = ["MeshWire agents (" + agents.length + "):"];
          for (const a of agents) {
            const me = a.agent_id === agentId ? " [YOU]" : "";
            const dot = a.status === "active" ? "*" : "-";
            lines.push("  " + dot + " " + a.name + me);
            lines.push("      id=" + a.agent_id + "  workspace=" + (a.workspace || "-"));
            lines.push("      last_seen=" + (a.last_seen || "-"));
          }
          return { textResultForLlm: lines.join("\\n"), resultType: "success" };
        } catch (err) {
          return { textResultForLlm: "[X] Failed to list agents: " + err.message, resultType: "failure" };
        }
      },
    },

    {
      name: "mesh_status",
      description: "Show MeshWire connection status -- registration state, agent ID, mesh info.",
      parameters: { type: "object", properties: {} },
      handler: async () => {
        const creds = loadCreds();
        const meshJson = loadMeshJson();
        const meshId = activeMeshId();
        let svc = "unknown";
        try {
          const r = await fetch(BASE_URL + "/health");
          const j = await r.json();
          svc = j.status || "unreachable";
        } catch { svc = "unreachable"; }
        const status = agentId ? "connected" : "disconnected";
        const lines = [
          "MeshWire status",
          "  connection : " + status,
          "  service    : " + svc,
          "  agent_id   : " + (agentId || "unregistered"),
          "  agent_name : " + (agentName || "-"),
          "  mesh_id    : " + (meshId || "-"),
          "  workspace  : " + (meshJson?.workspace_name || "-"),
          "  base_url   : " + BASE_URL,
          "  authed_as  : " + (creds?.login || "-"),
          "  heartbeat  : " + (heartbeatTimer ? "active" : "stopped"),
          "  polling    : " + (pollTimer ? "active" : "stopped"),
        ];
        return { textResultForLlm: lines.join("\\n"), resultType: "success" };
      },
    },
  ],
});

// --- Early registration ----------------------------------------------------
try {
  const result = await registerAgent();
  if (result) {
    startHeartbeat();
    startPolling();
    await session.log(
      "[meshwire] registered as \\"" + agentName + "\\" (id=" + agentId + ") -- heartbeat " +
      (HEARTBEAT_INTERVAL_MS / 1000) + "s, polling " + (POLL_INTERVAL_MS / 1000) + "s"
    );
  } else {
    await session.log("[meshwire] not registered (no .mesh.json or registration failed) -- run: meshwire init --harness copilot");
  }
} catch (err) {
  await session.log("[meshwire] startup error: " + err.message);
}
`;
}

// ---------------------------------------------------------------------------
// CLI-side setup (runs when user executes `meshwire init --harness copilot`)
// ---------------------------------------------------------------------------

export async function setupCopilot({ meshId, agentName, meshwireUrl, workspaceName }) {
  console.log('\n' + chalk.bold('Setting up Copilot CLI harness') + '\n');

  const creds = readCredentials();
  if (!creds?.token) {
    console.error(chalk.red('  [X] Not authenticated. Run `meshwire login` first.\n'));
    process.exit(1);
  }

  // 1. Create/update .mesh.json in the current workspace
  const existing = readMeshJson() || {};
  const meshJsonData = {
    mesh_id: meshId || existing.mesh_id,
    workspace_name: workspaceName || existing.workspace_name || process.cwd().split(/[/\\]/).pop(),
    agent_name: agentName || existing.agent_name || 'copilot-agent',
    harness: 'copilot',
  };

  if (!meshJsonData.mesh_id) {
    console.error(chalk.red('  [X] No mesh ID. Create a mesh first: meshwire mesh create\n'));
    process.exit(1);
  }

  writeMeshJson(meshJsonData);
  console.log(chalk.green('  [OK] .mesh.json written'));
  console.log(chalk.dim(`    mesh_id:    ${meshJsonData.mesh_id}`));
  console.log(chalk.dim(`    agent_name: ${meshJsonData.agent_name}`));
  console.log(chalk.dim(`    harness:    copilot`));

  // 2. Generate and write the Copilot extension
  mkdirSync(EXTENSION_DIR, { recursive: true });
  const source = buildExtensionSource({
    meshwireUrl: meshwireUrl || 'https://meshwire.io',
    meshId: meshJsonData.mesh_id,
  });
  writeFileSync(EXTENSION_FILE, source, 'utf8');
  console.log(chalk.green(`\n  [OK] Extension installed at ${EXTENSION_FILE}`));

  // 3. Register the agent in the mesh now
  console.log(chalk.dim('\n  Registering agent in mesh...'));
  try {
    const client = new MeshWireClient({ url: meshwireUrl, token: creds.token, meshId: meshJsonData.mesh_id });
    const agent = await client.registerAgent(meshJsonData.mesh_id, {
      name: meshJsonData.agent_name,
      description: 'GitHub Copilot CLI agent',
      workspace: meshJsonData.workspace_name,
      metadata: { platform: 'copilot-cli', harness: 'meshwire' },
    });
    console.log(chalk.green(`  [OK] Registered as ${agent.name} (${agent.agent_id})`));
  } catch (err) {
    console.log(chalk.yellow(`  [!] Could not register now: ${err.message}`));
    console.log(chalk.dim('    The extension will auto-register on next Copilot CLI session.'));
  }

  // 4. Print summary
  console.log('\n' + chalk.bold.green('  Copilot harness ready.\n'));
  console.log(chalk.dim('  The extension provides these tools in every Copilot session:'));
  console.log(chalk.cyan('    mesh_send_message')      + chalk.dim('     -- broadcast or target a specific agent'));
  console.log(chalk.cyan('    mesh_reply_to_message')  + chalk.dim(' -- reply to a specific message'));
  console.log(chalk.cyan('    mesh_get_messages')      + chalk.dim('     -- fetch recent messages'));
  console.log(chalk.cyan('    mesh_list_agents')       + chalk.dim('      -- discover agents in the mesh'));
  console.log(chalk.cyan('    mesh_status')            + chalk.dim('           -- check connection health'));
  console.log('');
  console.log(chalk.dim('  The .mesh.json file in this repo defines which mesh Copilot connects to.'));
  console.log(chalk.dim('  Commit .mesh.json so your teammates auto-join the same mesh.\n'));
}

// Exported for tests
export { buildExtensionSource };
