// Copilot CLI harness setup
// Generates a user-level Copilot extension at ~/.copilot/extensions/meshwire.mjs
// The extension reads credentials from ~/.meshwire/credentials.json and
// workspace config from .mesh.json in the current directory.

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import chalk from 'chalk';
import { writeMeshJson, readMeshJson } from '../mesh-schema.js';
import { readCredentials } from '../auth.js';
import { MeshWireClient } from '../api.js';

const EXTENSION_DIR = join(homedir(), '.copilot', 'extensions');
const EXTENSION_FILE = join(EXTENSION_DIR, 'meshwire.mjs');

// The generated extension template
function buildExtensionSource({ meshwireUrl }) {
  return `// MeshWire — Copilot CLI Extension
// Auto-generated by: meshwire init --harness copilot
// Reads credentials from ~/.meshwire/credentials.json
// Reads workspace mesh from .mesh.json in the current directory

import { readFileSync, existsSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

const CREDS_FILE = join(homedir(), '.meshwire', 'credentials.json');
const DEFAULT_URL = '${meshwireUrl}';

function loadCreds() {
  if (!existsSync(CREDS_FILE)) return null;
  try { return JSON.parse(readFileSync(CREDS_FILE, 'utf8')); } catch { return null; }
}

function loadMeshJson() {
  const file = join(process.cwd(), '.mesh.json');
  if (!existsSync(file)) return null;
  try { return JSON.parse(readFileSync(file, 'utf8')); } catch { return null; }
}

async function api(path, method = 'GET', body = null) {
  const creds = loadCreds();
  if (!creds?.token) throw new Error('Not authenticated. Run: meshwire login');
  const meshJson = loadMeshJson();
  const url = DEFAULT_URL + path.replace('{meshId}', meshJson?.mesh_id || '');
  const opts = {
    method,
    headers: {
      'Authorization': 'Bearer ' + creds.token,
      'Content-Type': 'application/json',
    },
  };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(url, opts);
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    let msg; try { msg = JSON.parse(txt).error; } catch { msg = txt || res.statusText; }
    throw new Error(msg);
  }
  return res.json();
}

// ΓöÇΓöÇΓöÇ Tool Definitions ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const tools = [
  {
    name: 'mesh_send_message',
    description: 'Send a message to agents in the mesh. Use recipient_id "*" to broadcast.',
    parameters: {
      type: 'object',
      properties: {
        content: { type: 'string', description: 'Message content' },
        recipient_id: { type: 'string', default: '*', description: 'Target agent ID or "*" for all' },
        priority: { type: 'string', enum: ['urgent', 'high', 'normal', 'low'], default: 'normal' },
      },
      required: ['content'],
    },
    async execute({ content, recipient_id = '*', priority = 'normal' }) {
      const creds = loadCreds();
      const meshJson = loadMeshJson();
      if (!meshJson?.mesh_id) throw new Error('No mesh configured. Add .mesh.json to this workspace.');
      const agent_id = creds?.agentId || 'copilot-cli';
      const msg = await api(
        '/mesh/{meshId}/messages', 'POST',
        { sender_id: agent_id, recipient_id, content, priority }
      );
      return { sent: true, message_id: msg.message_id, to: recipient_id };
    },
  },

  {
    name: 'mesh_get_messages',
    description: 'Fetch new messages from the mesh. Uses long-polling (up to 10s).',
    parameters: {
      type: 'object',
      properties: {
        offset: { type: 'integer', default: 0, description: 'Return messages with ID > offset' },
        timeout: { type: 'integer', default: 10, description: 'Poll timeout in seconds (max 30)' },
      },
    },
    async execute({ offset = 0, timeout = 10 }) {
      const creds = loadCreds();
      const meshJson = loadMeshJson();
      if (!meshJson?.mesh_id) throw new Error('No mesh configured. Add .mesh.json to this workspace.');
      const agentId = creds?.agentId || undefined;
      const params = new URLSearchParams({ offset: String(offset), timeout: String(Math.min(timeout, 30)) });
      if (agentId) params.set('recipient', agentId);
      const result = await api('/mesh/{meshId}/messages?' + params.toString());
      if (!result.messages?.length) return { messages: [], count: 0 };
      return {
        count: result.count,
        messages: result.messages.map(m => ({
          id: m.message_id,
          from: m.sender_id,
          to: m.recipient_id,
          content: m.content,
          priority: m.priority,
          time: m.created_at,
        })),
      };
    },
  },

  {
    name: 'mesh_reply_to_message',
    description: 'Reply to a specific message in the mesh. Sends the reply to the original sender and links it via metadata.reply_to.',
    parameters: {
      type: 'object',
      properties: {
        message_id: { type: 'integer', description: 'message_id of the original message to reply to' },
        content: { type: 'string', description: 'Reply content (max 10KB)' },
      },
      required: ['message_id', 'content'],
    },
    async execute({ message_id, content }) {
      const creds = loadCreds();
      const meshJson = loadMeshJson();
      if (!meshJson?.mesh_id) throw new Error('No mesh configured. Add .mesh.json to this workspace.');
      const sender_id = creds?.agentId || globalThis.__meshwire_agent_id__ || 'copilot-cli';
      const reply = await api(
        '/mesh/{meshId}/messages/' + message_id + '/reply',
        'POST',
        { sender_id, content }
      );
      return { sent: true, reply_id: reply.message_id, reply_to: message_id, to: reply.recipient_id };
    },
  },

  {
    name: 'mesh_list_agents',
    description: 'List all agents currently registered in this workspace mesh.',
    parameters: { type: 'object', properties: {} },
    async execute() {
      const meshJson = loadMeshJson();
      if (!meshJson?.mesh_id) throw new Error('No mesh configured. Add .mesh.json to this workspace.');
      const result = await api('/mesh/{meshId}/agents');
      return {
        count: result.count,
        agents: result.agents.map(a => ({
          id: a.agent_id,
          name: a.name,
          status: a.status,
          workspace: a.workspace,
          last_seen: a.last_seen,
        })),
      };
    },
  },

  {
    name: 'mesh_status',
    description: 'Check MeshWire connection status and current mesh/agent info.',
    parameters: { type: 'object', properties: {} },
    async execute() {
      const creds = loadCreds();
      const meshJson = loadMeshJson();
      const health = await fetch(DEFAULT_URL + '/health').then(r => r.json()).catch(() => null);
      return {
        authenticated: Boolean(creds?.token),
        login: creds?.login || null,
        mesh_id: meshJson?.mesh_id || null,
        workspace: meshJson?.workspace_name || null,
        agent_name: meshJson?.agent_name || null,
        service: health?.status || 'unreachable',
      };
    },
  },
];

// ΓöÇΓöÇΓöÇ Hooks ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const hooks = {
  // Called on session start — register this agent in the mesh
  async onSessionStart({ agentName } = {}) {
    const creds = loadCreds();
    const meshJson = loadMeshJson();
    if (!creds?.token || !meshJson?.mesh_id) return;

    const name = agentName || meshJson?.agent_name || 'copilot-cli';
    try {
      const agent = await api('/mesh/{meshId}/agents', 'POST', {
        name,
        description: 'GitHub Copilot CLI agent',
        workspace: process.cwd().split('/').pop() || 'workspace',
        metadata: { platform: 'copilot-cli', harness: 'meshwire' },
      });
      // Store agent ID in a runtime variable for this session
      if (typeof globalThis !== 'undefined') {
        globalThis.__meshwire_agent_id__ = agent.agent_id;
      }
      console.log('[meshwire] Registered as ' + name + ' (' + agent.agent_id + ')');
    } catch (err) {
      console.warn('[meshwire] Could not register agent:', err.message);
    }
  },

  // Called periodically — keep heartbeat alive
  async onHeartbeat() {
    const creds = loadCreds();
    const meshJson = loadMeshJson();
    const agentId = globalThis.__meshwire_agent_id__;
    if (!creds?.token || !meshJson?.mesh_id || !agentId) return;
    await api('/mesh/{meshId}/agents/' + agentId + '/heartbeat', 'POST').catch(() => {});
  },
};
`;
}

export async function setupCopilot({ meshId, agentName, meshwireUrl, workspaceName }) {
  console.log('\n' + chalk.bold('⚙️  Setting up Copilot CLI harness') + '\n');

  const creds = readCredentials();
  if (!creds?.token) {
    console.error(chalk.red('  ✗ Not authenticated. Run `meshwire login` first.\n'));
    process.exit(1);
  }

  // 1. Create/update .mesh.json in the current workspace
  const existing = readMeshJson() || {};
  const meshJsonData = {
    mesh_id: meshId || existing.mesh_id,
    workspace_name: workspaceName || existing.workspace_name || process.cwd().split(/[/\\]/).pop(),
    agent_name: agentName || existing.agent_name || 'copilot-agent',
    harness: 'copilot',
  };

  if (!meshJsonData.mesh_id) {
    console.error(chalk.red('  ✗ No mesh ID. Create a mesh first: meshwire mesh create\n'));
    process.exit(1);
  }

  writeMeshJson(meshJsonData);
  console.log(chalk.green('  ✔ .mesh.json written'));
  console.log(chalk.dim(`    mesh_id:    ${meshJsonData.mesh_id}`));
  console.log(chalk.dim(`    agent_name: ${meshJsonData.agent_name}`));
  console.log(chalk.dim(`    harness:    copilot`));

  // 2. Generate and write the Copilot extension
  mkdirSync(EXTENSION_DIR, { recursive: true });
  const source = buildExtensionSource({ meshwireUrl: meshwireUrl || 'https://meshwire.io' });
  writeFileSync(EXTENSION_FILE, source, 'utf8');
  console.log(chalk.green(`\n  ✔ Extension installed at ${EXTENSION_FILE}`));

  // 3. Register the agent in the mesh now
  console.log(chalk.dim('\n  Registering agent in mesh...'));
  try {
    const client = new MeshWireClient({ url: meshwireUrl, token: creds.token, meshId: meshJsonData.mesh_id });
    const agent = await client.registerAgent(meshJsonData.mesh_id, {
      name: meshJsonData.agent_name,
      description: 'GitHub Copilot CLI agent',
      workspace: meshJsonData.workspace_name,
      metadata: { platform: 'copilot-cli', harness: 'meshwire' },
    });
    console.log(chalk.green(`  ✔ Registered as ${agent.name} (${agent.agent_id})`));
  } catch (err) {
    console.log(chalk.yellow(`  ΓÜá Could not register now: ${err.message}`));
    console.log(chalk.dim('    The extension will auto-register on next Copilot CLI session.'));
  }

  // 4. Print summary
  console.log('\n' + chalk.bold.green('  ✓ Copilot harness ready!\n'));
  console.log(chalk.dim('  The extension provides these tools in every Copilot session:'));
  console.log(chalk.cyan('    mesh_send_message') + chalk.dim('   — broadcast or target a specific agent'));
  console.log(chalk.cyan('    mesh_get_messages') + chalk.dim('   — poll for new messages'));
  console.log(chalk.cyan('    mesh_list_agents') + chalk.dim('    — discover agents in the mesh'));
  console.log(chalk.cyan('    mesh_status') + chalk.dim('         — check connection health'));
  console.log('');
  console.log(chalk.dim('  The .mesh.json file in this repo defines which mesh Copilot connects to.'));
  console.log(chalk.dim('  Commit .mesh.json so your teammates auto-join the same mesh.\n'));
}
